export const retentionCopy = {
  "zh-CN": {
    title: "记录与保留策略", description: "修改全站记录策略。保存设置与立即清理是两个独立操作。",
    logs: "运行日志保留天数", events: "事件保留天数", calls: "调用记录保留天数", days: "天", revision: "策略修订",
    defaults: "默认各保留 7 天；调用输入、输出内容随调用记录一起到期。",
    mode: "调用内容记录", metadata: "仅元数据（默认）", redacted: "记录脱敏后的内容",
    privacy: "敏感字段会脱敏，但不能保证识别所有业务秘密。开启内容记录仅影响后续调用，历史未记录内容无法补回。",
    disabled: "清理工作进程未启用，立即清理不可用。仍可保存策略；保存不会触发清理。",
    enabled: "清理工作进程已启用。保存本身不会启动清理任务；后台执行已提交的清理任务。",
    save: "保存策略", saved: "策略已保存；未请求立即清理。", refresh: "重新读取策略", retained: "已重新读取策略；尚未保存的输入已保留，请核对修订及影响。",
    shrinkTitle: "确认缩短保留时间？", shrinkDescription: "以下是按新策略计算的到期数据。缩短会扩大后续清理范围，删除后无法恢复。本次仅保存策略，不启动立即清理。",
    cleanup: "立即清理", cleanupTitle: "确认立即清理到期记录？", cleanupDescription: "仅清理本次预览所绑定修订和截止时间前的记录。删除无法恢复；不会删除服务配置或项目制品。",
    table: "记录类型", cutoff: "截止时间（UTC）", count: "预览到期条数", expires: "预览有效至", notCount: "不是全量记录统计。",
    cleanDraft: "请先保存或放弃策略修改，再按已保存策略清理。", loading: "正在读取策略…", reloadRequired: "无法确认当前服务端策略，请重新读取后再操作。",
    jobCancel: "取消清理任务", jobCancelTitle: "停止后续清理批次？", jobCancelDescription: "取消只能停止后续批次；已删除的记录无法恢复。", jobCancelled: "清理任务已取消；已删除的批次无法恢复。",
    job: "清理任务", jobRefresh: "刷新任务状态", queued: "已提交清理任务；尚未确认清理完成。", jobDone: "清理任务已完成。", jobFailed: "清理任务失败或已取消，请查看任务结果。", noPolling: "任务状态仅在手动刷新时更新。", result: "任务结果", cancel: "取消", saveFailed: "保存结果未获确认，请重新读取策略。", previewStale: "预览已过期或策略已改变，请重新预览。", invalid: "保留天数必须是允许范围内的整数。",
  },
  "en-US": {
    title: "Recording and retention", description: "Configure recording across Gate. Saving policy and immediate cleanup are separate actions.",
    logs: "Runtime log retention days", events: "Event retention days", calls: "Invocation retention days", days: "days", revision: "Policy revision",
    defaults: "Each defaults to 7 days. Recorded inputs and outputs expire with their invocation records.",
    mode: "Invocation content recording", metadata: "Metadata only (default)", redacted: "Record redacted content",
    privacy: "Sensitive fields are redacted, but not all business secrets can be recognized. Recording applies to future calls; previously unrecorded content cannot be recovered.",
    disabled: "The cleanup worker is disabled; immediate cleanup is unavailable. Policy can still be saved without starting cleanup.",
    enabled: "The cleanup worker is enabled. Saving does not start a cleanup job; submitted cleanup jobs run in the background.",
    save: "Save policy", saved: "Policy saved; immediate cleanup was not requested.", refresh: "Reload policy", retained: "Policy reloaded; your unsaved inputs were retained. Review the revision and impact.",
    shrinkTitle: "Shorten retention?", shrinkDescription: "This preview shows records expiring under the proposed policy. Shortening expands future cleanup; deletion cannot be undone. This action only saves policy and does not start immediate cleanup.",
    cleanup: "Clean up now", cleanupTitle: "Delete expired records now?", cleanupDescription: "Delete only records before the cutoffs bound to this preview and revision. Deletion cannot be undone. Service configuration and project artifacts are excluded.",
    table: "Record type", cutoff: "Cutoff (UTC)", count: "Expired records in preview", expires: "Preview expires", notCount: "Not an all-time record count.",
    cleanDraft: "Save or discard policy changes before cleaning up under the saved policy.", loading: "Loading policy…", reloadRequired: "The current server policy is unconfirmed. Reload it before proceeding.",
    jobCancel: "Cancel cleanup job", jobCancelTitle: "Stop further cleanup batches?", jobCancelDescription: "Cancellation stops future batches only. Records already deleted cannot be restored.", jobCancelled: "Cleanup job cancelled; previously deleted batches cannot be restored.",
    job: "Cleanup job", jobRefresh: "Refresh job status", queued: "Cleanup job submitted; completion is not yet confirmed.", jobDone: "Cleanup job completed.", jobFailed: "Cleanup job failed or was cancelled. Review the job result.", noPolling: "Job status updates only on manual refresh.", result: "Job result", cancel: "Cancel", saveFailed: "Save result is unconfirmed. Reload the policy.", previewStale: "The preview expired or policy changed. Preview again.", invalid: "Retention days must be integers within the allowed range.",
  },
}
