import { Button } from "antd"
import type { RefObject } from "react"
import { FormDialog } from "@/components/form-dialog"
import type { OAuthConfig } from "./oauth-api"

/** On-demand setup guidance. Contains public metadata only, never signing secrets. */
export function OAuthConnectionGuide({ open, onClose, config, zh, trigger }: { open: boolean; onClose: () => void; config: OAuthConfig | null; zh: boolean; trigger: RefObject<HTMLButtonElement | null> }) {
  return <FormDialog open={open} onClose={onClose} title={zh ? "接入指引" : "Connection guide"} closeLabel={zh ? "关闭" : "Close"} className="oauth-guide-dialog" bodyClassName="oauth-guide-body" onCloseAutoFocus={event => { if (trigger.current?.isConnected) { event.preventDefault(); trigger.current.focus({ preventScroll: true }) } }} footer={<Button onClick={onClose}>{zh ? "关闭" : "Close"}</Button>}>
    <section><h2>{zh ? "连接地址" : "Connection URLs"}</h2><p>{zh ? "Issuer 必须是 HTTPS 域名，无路径或末尾斜线。MCP 资源固定使用 /mcp，是客户端实际连接地址，不是 OAuth 回调。有效 Issuer 仅自动填写空值或上次自动填写的资源；手动修改会保留。已启用时，先关闭 OAuth 才能修改地址；已有连接需要重新授权。" : "Issuer must be an HTTPS origin with no path or trailing slash. The MCP resource uses /mcp: the client's connection address, not an OAuth callback. A valid issuer fills only an empty or previously automatic resource; manual edits are retained. Disable OAuth before changing enabled URLs; existing connections need new authorization."}</p></section>
    <section><h2>{zh ? "客户端与回调" : "Clients and callbacks"}</h2><p>{zh ? "从 ChatGPT 连接管理页复制精确 HTTPS 回调；在支持预定义客户端的配置入口填写 Client ID 和密钥。无需 CIMD 或匿名注册。客户端密钥仅展示一次，保存到客户端的安全秘密配置中。轮换旧密钥立即失效，并撤销该客户端的现有令牌族。" : "Copy the exact HTTPS callback from ChatGPT connection settings; enter Client ID and secret in the setup that supports predefined clients. CIMD and anonymous registration are not used. A client secret is shown once: store it in the client's secure secret configuration. Rotation immediately invalidates the old secret and revokes that client's existing token families."}</p></section>
    <section><h2>{zh ? "TLS 与公开路径" : "TLS and public paths"}</h2><p>{zh ? "启用前核对 TLS、公开路径和回调。代理仅放行业务 /mcp、OAuth 发现及 /oauth/ 页面与协议端点；启用独立管理连接时另放行 /mcp/manage 及其路径专用资源元数据。Console 与 /v1 继续仅供内部管理。签名私钥加密保存，不会输出；轮换时旧公钥保留 10 分钟用于验证已有访问令牌。" : "Review TLS, public paths and callbacks before enabling. Allow business /mcp, OAuth discovery and pages/protocol under /oauth/. Separately enabled management also needs /mcp/manage and its path-specific resource metadata. Keep Console and /v1 private. Signing private keys are encrypted and never returned; rotation retains old public keys for 10 minutes to verify existing access tokens."}</p>
      {config && <dl className="oauth-endpoints">{[["Issuer", config.issuer], [zh ? "MCP 资源" : "MCP resource", config.resource], ["Discovery", config.metadata_url], ["Authorize", config.authorization_endpoint], ["Token", config.token_endpoint], ["JWKS", config.jwks_uri]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "—"}</dd></div>)}</dl>}
    </section>
    <section><h2>{zh ? "授权与连接验收" : "Authorization and connection verification"}</h2><p>{zh ? "管理员不能代用户同意授权；每个用户仍须登录 Gate 并选择工具。工具发现不授予权限，各令牌族保留自己的 OAuth scope 上限。独立管理资源固定为 /mcp/manage，默认关闭；客户端须新建管理连接，请求 operations.manage，由当前管理员逐项同意四个外部配置工具及精确创建/更新目标，业务连接不会升级。保存配置和启用服务都不代表外部连接验收，请另行验证只读调用、拒绝范围、到期与撤权。" : "Administrators cannot consent for users: each user signs in to Gate and selects tools. Discovery does not grant access; every token family retains its OAuth scope ceiling. The separate management resource uses /mcp/manage and is disabled by default. The client creates a new management connection requesting operations.manage; a current administrator approves the four external configuration tools and exact create/update targets. Business connections are unchanged. Saving or enabling is not external connection verification. Separately verify read calls, denied scope, expiry and revocation."}</p></section>
    <a href="https://github.com/zhigege666/Lingshu-Gate/blob/main/docs/builtin-oauth.md" target="_blank" rel="noreferrer">{zh ? "内置 OAuth 配置说明" : "Built-in OAuth setup"}</a>
  </FormDialog>
}
