import type { ControlPermission } from "@/api/client"
import type { Locale } from "@/i18n"

export const accessRolesCopy = {
  "zh-CN": {
    source: "来源", allSources: "全部来源", allStatuses: "全部状态", allLevels: "全部级别",
    searchRoles: "搜索角色名称或标识", searchTypes: "搜索权限类型名称或标识",
    view: "查看", copy: "复制", copySuffix: "副本", enable: "启用", disable: "停用", enabledStatus: "已启用", disabledStatus: "已停用",
    roleDetails: "角色详情", typeDetails: "权限类型详情", closeDetails: "关闭详情", managementTabs: "管理类别",
    permissionCount: "项权限", permissionsHint: "该角色包含以下菜单与操作权限。", noPermissions: "未分配菜单与操作权限",
    noMatches: "未找到匹配项", resetFilters: "清除筛选", total: "共", items: "项", loading: "正在加载角色与权限类型…",
    assignedRole: "请先移除该角色的成员，再删除角色。", referencedType: "请先移除相关资源授权，再删除权限类型。",
    disableRoleHint: "停用后，成员将不再获得该角色提供的权限。", disableTypeHint: "停用后，使用此类型的资源授权将不再生效。",
    manageTypes: "管理权限类型", manageRoles: "管理角色", rolesHint: "权限类型用于 MCP 服务和工具的资源授权。", typesHint: "角色定义后台菜单与操作能力。",
    emptyDescription: "暂无说明", duplicateCode: "该标识已存在，请换一个。", requiredFields: "请填写名称和代码。", requiredCode: "请输入有效代码。", requiredName: "请输入名称。",
    codeHint: "仅支持小写字母、数字、下划线、点和横线。", invalidCode: "代码格式不正确，仅支持小写字母、数字、下划线、点和横线。",
    discardTitle: "放弃尚未保存的修改？", discardDescription: "关闭后将清除本次修改，已保存的角色或权限类型不变。", discardChanges: "放弃修改", continueEditing: "继续编辑", saving: "正在保存…", selectedPermissions: "已选权限", systemRoleRestricted: "系统内置角色的代码和启用状态不能修改。", systemTypeRestricted: "系统内置权限类型的代码、启用状态和基础级别不能修改。",
    eyebrow: "安全与访问 · 策略模型",
    title: "角色与权限类型",
    description: "角色定义控制台能做什么；权限类型定义 MCP 资源授权的语义级别。两者分离，避免把页面管理权限和工具读写权限混在一起。",
    roles: "角色",
    roleDesc: "按菜单和操作能力组合权限，可分配给多个用户。",
    permissionTypes: "权限类型",
    permissionTypeDesc: "映射到无权限 / 只读 / 读写基础级别，供 MCP 服务或工具授权使用。",
    newRole: "新建角色",
    editRole: "编辑角色",
    newType: "新建权限类型",
    editType: "编辑权限类型",
    code: "代码",
    name: "名称",
    descriptionLabel: "说明",
    members: "成员",
    controlPermissions: "菜单与操作权限",
    baseLevel: "基础级别",
    references: "授权引用",
    enabled: "启用",
    system: "系统内置",
    custom: "自定义",
    noRoles: "暂无角色",
    noTypes: "暂无权限类型",
    save: "保存",
    deleteRole: "删除角色",
    deleteType: "删除权限类型",
    noneLevel: "无权限",
    readLevel: "只读",
    writeLevel: "读写",
  },
  "en-US": {
    source: "Source", allSources: "All sources", allStatuses: "All statuses", allLevels: "All levels",
    searchRoles: "Search role name or code", searchTypes: "Search permission type name or code",
    view: "View", copy: "Copy", copySuffix: " copy", enable: "Enable", disable: "Disable", enabledStatus: "Enabled", disabledStatus: "Disabled",
    roleDetails: "Role details", typeDetails: "Permission type details", closeDetails: "Close details", managementTabs: "Management category",
    permissionCount: "permissions", permissionsHint: "This role includes the following console permissions.", noPermissions: "No control permissions assigned",
    noMatches: "No matching items", resetFilters: "Clear filters", total: "Total", items: "items", loading: "Loading roles and permission types…",
    assignedRole: "Remove this role's members before deleting it.", referencedType: "Remove resource grants that reference this type before deleting it.",
    disableRoleHint: "Members will no longer receive permissions from this role.", disableTypeHint: "Resource grants using this type will no longer take effect.",
    manageTypes: "Manage permission types", manageRoles: "Manage roles", rolesHint: "Permission types apply to MCP server and tool grants.", typesHint: "Roles define console menu and action capabilities.",
    emptyDescription: "No description", duplicateCode: "This code already exists. Choose another code.", requiredFields: "Enter a name and code.", requiredCode: "Enter a valid code.", requiredName: "Enter a name.",
    codeHint: "Use lowercase letters, numbers, underscores, dots, or hyphens.", invalidCode: "Use only lowercase letters, numbers, underscores, dots, or hyphens in the code.",
    discardTitle: "Discard unsaved changes?", discardDescription: "Closing clears these changes. The saved role or permission type is unchanged.", discardChanges: "Discard changes", continueEditing: "Continue editing", saving: "Saving…", selectedPermissions: "Selected permissions", systemRoleRestricted: "Built-in role codes and enabled status cannot be changed.", systemTypeRestricted: "Built-in permission type codes, enabled status, and base levels cannot be changed.",
    eyebrow: "SECURITY & ACCESS · POLICY MODEL",
    title: "Roles & Permission Types",
    description: "Roles define console capabilities; permission types define MCP resource access semantics. Keeping them separate avoids mixing administration and tool access.",
    roles: "Roles",
    roleDesc: "Bundle control-plane permissions and assign them to users.",
    permissionTypes: "Permission types",
    permissionTypeDesc: "Map to none / read / write and apply to MCP server or tool grants.",
    newRole: "New role",
    editRole: "Edit role",
    newType: "New permission type",
    editType: "Edit permission type",
    code: "Code",
    name: "Name",
    descriptionLabel: "Description",
    members: "Members",
    controlPermissions: "Control permissions",
    baseLevel: "Base level",
    references: "Grant references",
    enabled: "Enabled",
    system: "System",
    custom: "Custom",
    noRoles: "No roles",
    noTypes: "No permission types",
    save: "Save",
    deleteRole: "Delete role",
    deleteType: "Delete permission type",
    noneLevel: "None",
    readLevel: "Read",
    writeLevel: "Read & write",
  },
} satisfies Record<Locale, Record<string, string>>

type ControlPermissionPresentation = {
  name: string
  description: string
  group: string
}

const controlPermissionPresentations: Record<Locale, Record<string, ControlPermissionPresentation>> = {
  "zh-CN": {
    "console.view": { name: "仪表盘与基础控制台", description: "登录并查看仪表盘及基础控制台信息。", group: "控制台基础" },
    "users.manage": { name: "用户管理", description: "查看用户，并审核、启用、停用或维护账号。", group: "身份与授权" },
    "roles.manage": { name: "角色与权限类型", description: "维护角色、菜单与操作权限，以及 MCP 权限类型。", group: "身份与授权" },
    "grants.manage": { name: "资源授权", description: "维护用户和角色的 MCP 服务或工具授权。", group: "身份与授权" },
    "classifications.manage": { name: "工具读写分类", description: "分析、确认并发布工具的只读或读写分类。", group: "身份与授权" },
    "credentials.manage.self": { name: "我的 API Token 与下游凭据", description: "维护自己的 Lingshu Gate API Token 和下游 MCP 凭据。", group: "凭据与审计" },
    "credentials.manage.all": { name: "全部用户 API Token", description: "查看并吊销全部用户的 API Token，不读取用户下游秘密。", group: "凭据与审计" },
    "audit.read": { name: "调用审计", description: "查看 MCP 调用的授权判定和执行结果。", group: "凭据与审计" },
    "tools.read": { name: "工具", description: "发现获准使用的 MCP 工具。", group: "工具调用与运行态" },
    "tools.invoke": { name: "调用", description: "调用获准使用的只读或写入 MCP 工具。", group: "工具调用与运行态" },
    "operations.manage": { name: "配置与运维管理", description: "管理 MCP 配置、服务、构建部署、运行缓存、上传和诊断等页面。", group: "工具调用与运行态" },
  },
  "en-US": {
    "console.view": { name: "Dashboard & console", description: "Sign in and view the dashboard and basic console information.", group: "Console basics" },
    "users.manage": { name: "User management", description: "Review, activate, disable, and maintain user accounts.", group: "Identity & access" },
    "roles.manage": { name: "Roles & permission types", description: "Manage roles, menu and action permissions, and MCP permission types.", group: "Identity & access" },
    "grants.manage": { name: "Resource grants", description: "Manage MCP server or tool grants for users and roles.", group: "Identity & access" },
    "classifications.manage": { name: "Tool classification", description: "Analyze, confirm, and publish read or write classifications for tools.", group: "Identity & access" },
    "credentials.manage.self": { name: "My API tokens & downstream credentials", description: "Manage personal Lingshu Gate API tokens and downstream MCP credentials.", group: "Credentials & audit" },
    "credentials.manage.all": { name: "All user API tokens", description: "View and revoke user API tokens without reading downstream secrets.", group: "Credentials & audit" },
    "audit.read": { name: "Invocation audit", description: "Review MCP authorization decisions and invocation results.", group: "Credentials & audit" },
    "tools.read": { name: "Tools", description: "Discover MCP tools the user is allowed to access.", group: "Tools & runtime" },
    "tools.invoke": { name: "Invoke", description: "Invoke allowed read-only or write MCP tools.", group: "Tools & runtime" },
    "operations.manage": { name: "Configuration & operations", description: "Manage MCP configuration, services, builds, runtime cache, uploads, and diagnostics.", group: "Tools & runtime" },
  },
}

export function presentControlPermission(permission: ControlPermission, locale: Locale): ControlPermissionPresentation {
  return controlPermissionPresentations[locale][permission.code] || {
    name: permission.name || permission.code,
    description: permission.description,
    group: locale === "zh-CN" ? "其他权限" : "Other permissions",
  }
}
