import type { TFunction } from "@/i18n"

const zh: Record<string, string> = {
  workspaceNavigation: "构建部署导航",
  workspaceTab: "当前工作台",
  buildsTab: "构建记录",
  deploymentsTab: "部署记录",
  logsTab: "日志与输出",
  projectContext: "项目上下文",
  projectContextDesc: "围绕当前项目执行预检、构建和部署；历史记录在独立标签页查看。",
  latestBuild: "最新构建",
  latestDeployment: "最近部署",
  noBuild: "暂无构建",
  notDeployed: "尚未部署",
  advancedSettings: "高级设置（运行时、根目录与服务 ID）",
  deploymentOptions: "部署选项",
  deploymentSummary: "部署确认摘要",
  deploymentTarget: "目标服务",
  overwriteExisting: "覆盖已有配置",
  overwriteExistingDesc: "默认关闭。仅在明确确认要替换同 ID 配置时开启。",
  startAfterDeploy: "部署后启动",
  startAfterDeployDesc: "默认关闭。部署只持久化并应用配置，不自动启动服务。",
  startAfterRollback: "回滚后启动",
  startAfterRollbackDesc: "默认关闭。回滚恢复配置后保持服务停止。",
  enabledChoice: "是",
  disabledChoice: "否",
  confirmDeploymentTitle: "确认部署构建？",
  confirmRollbackTitle: "确认回滚部署？",
  rollbackSummary: "回滚确认摘要",
  restoresSnapshot: "覆盖恢复旧配置",
  unavailableTarget: "未解析",
  moreActions: "更多",
  view: "查看",
  viewLogs: "查看日志",
  retryBuild: "重新构建",
  deleteRecord: "删除记录",
  deleteUpload: "删除项目",
  deleteUploadTitle: "删除项目上传记录？",
  deleteUploadDesc: "仅当不存在构建记录时才允许删除，并会清理项目源文件与预检缓存。",
  deleteBuildTitle: "删除构建记录？",
  deleteBuildDesc: "将删除构建日志和构建产物。已部署或仍被 MCP 配置引用的构建会被拒绝删除。",
  deleteDeploymentTitle: "删除部署历史？",
  deleteDeploymentDesc: "不会停止服务，但会删除该次部署的回滚快照，之后不能再用它回滚。",
  deleteSuccess: "删除完成",
  buildPreflight: "构建预检",
  preflightDesc: "创建 Build 前检查项目根目录、运行时、入口点和本机工具链。",
  projectRoot: "项目根目录",
  projectRootPlaceholder: "默认为压缩包根目录，可留空或填 .",
  timelineQueued: "排队中",
  timelinePrepare: "准备",
  timelinePrepareDone: "已复制源码并启动 worker",
  timelineWaiting: "等待中",
  timelineCommands: "命令",
  commandLogs: "条命令日志",
  runtimeAuto: "自动识别运行时",
  runtimeNode: "Node",
  runtimePython: "Python",
  runPreflight: "运行预检",
  preflightStatus: "预检状态",
  preflightRuntime: "预检运行时",
  preflightRecommendations: "修复建议",
  preflightBlocked: "预检存在错误，已停止创建 Build。",
  preflightManualRuntimeRequired: "运行时无法自动识别，请手动选择 Node 或 Python 后再创建 Build。",
  buildBlocked: "构建被门禁拦截",
  detected: "识别为",
  toolStatus: "工具链状态",
  available: "可用",
  missing: "缺失",
  packageScripts: "package.json 脚本",
  noScripts: "未发现 build/start/dev 脚本",
  forceRefresh: "强制重检",
  cacheHit: "缓存命中",
  cacheMiss: "已重新检测",
  reusedTools: "复用工具探测",
  reusedToolsHint: "工具链未变化，已复用上次工具探测结果，跳过 --version 子进程。",
  changesSinceLast: "相对上次的变更",
  fileCountDelta: "文件数变化",
  affectedChecks: "受影响检查项",
  previewPlan: "预览构建计划",
  buildPlan: "构建计划 (IR)",
  buildPlanDesc: "由 Preflight 编译出的显式构建计划：有序步骤 + 产物策略 + manifest 策略。",
  buildable: "可构建",
  notBuildable: "不可构建",
  artifactStrategy: "产物策略",
  planSteps: "构建步骤",
  noSteps: "无需安装/构建步骤",
  phase: "阶段",
  reason: "原因",
  manifestStrategy: "Manifest 策略",
  resolveAfterBuild: "构建后解析入口",
  dependsOn: "依赖",
  autoDescended: "已自动定位到嵌套项目根目录",
}

const en: Record<string, string> = {
  workspaceNavigation: "Build and deploy navigation",
  workspaceTab: "Workspace",
  buildsTab: "Build history",
  deploymentsTab: "Deployment history",
  logsTab: "Logs and output",
  projectContext: "Project context",
  projectContextDesc: "Run preflight, build, and deploy for the selected project; history is available in separate tabs.",
  latestBuild: "Latest build",
  latestDeployment: "Latest deployment",
  noBuild: "No build yet",
  notDeployed: "Not deployed",
  advancedSettings: "Advanced settings (runtime, root, server ID)",
  deploymentOptions: "Deployment options",
  deploymentSummary: "Deployment confirmation summary",
  deploymentTarget: "Target server",
  overwriteExisting: "Overwrite existing config",
  overwriteExistingDesc: "Off by default. Enable only after confirming that the same-ID config should be replaced.",
  startAfterDeploy: "Start after deploy",
  startAfterDeployDesc: "Off by default. Deployment persists and applies the config without starting the server.",
  startAfterRollback: "Start after rollback",
  startAfterRollbackDesc: "Off by default. Rollback restores the config and leaves the server stopped.",
  enabledChoice: "Yes",
  disabledChoice: "No",
  confirmDeploymentTitle: "Confirm build deployment?",
  confirmRollbackTitle: "Confirm deployment rollback?",
  rollbackSummary: "Rollback confirmation summary",
  restoresSnapshot: "Overwrite with previous config",
  unavailableTarget: "Unresolved",
  moreActions: "More",
  view: "View",
  viewLogs: "View logs",
  retryBuild: "Rebuild",
  deleteRecord: "Delete record",
  deleteUpload: "Delete project",
  deleteUploadTitle: "Delete project upload?",
  deleteUploadDesc: "Deletion is allowed only without build history and also removes source files and preflight cache.",
  deleteBuildTitle: "Delete build record?",
  deleteBuildDesc: "Build logs and artifacts will be removed. Deployed or configured builds are protected.",
  deleteDeploymentTitle: "Delete deployment history?",
  deleteDeploymentDesc: "The running service is not stopped, but this deployment's rollback snapshot will be lost.",
  deleteSuccess: "Deleted",
  buildPreflight: "Build Preflight",
  preflightDesc: "Check project root, runtime, entrypoint, and local tools before Build.",
  projectRoot: "Project root",
  projectRootPlaceholder: "Defaults to the archive root; leave empty or use .",
  timelineQueued: "queued",
  timelinePrepare: "prepare",
  timelinePrepareDone: "source copied and worker started",
  timelineWaiting: "waiting",
  timelineCommands: "commands",
  commandLogs: "command log(s)",
  runtimeAuto: "Auto runtime",
  runtimeNode: "Node",
  runtimePython: "Python",
  runPreflight: "Run Preflight",
  preflightStatus: "Preflight Status",
  preflightRuntime: "Preflight Runtime",
  preflightRecommendations: "Fix Suggestions",
  preflightBlocked: "Preflight has errors. Build was not created.",
  preflightManualRuntimeRequired: "Runtime could not be detected. Select Node or Python before creating the Build.",
  buildBlocked: "Build blocked by gate",
  detected: "detected",
  toolStatus: "Toolchain Status",
  available: "available",
  missing: "missing",
  packageScripts: "package.json scripts",
  noScripts: "No build/start/dev script found",
  forceRefresh: "Force Refresh",
  cacheHit: "Cache hit",
  cacheMiss: "Recomputed",
  reusedTools: "Reused tool probes",
  reusedToolsHint: "Toolchain unchanged; reused the previous tool probe results and skipped --version subprocesses.",
  changesSinceLast: "Changes since last run",
  fileCountDelta: "File count delta",
  affectedChecks: "Affected checks",
  previewPlan: "Preview Plan",
  buildPlan: "Build Plan (IR)",
  buildPlanDesc: "Explicit build plan compiled from Preflight: ordered steps + artifact strategy + manifest strategy.",
  buildable: "Buildable",
  notBuildable: "Not buildable",
  artifactStrategy: "Artifact strategy",
  planSteps: "Build steps",
  noSteps: "No install/build step required",
  phase: "Phase",
  reason: "Reason",
  manifestStrategy: "Manifest strategy",
  resolveAfterBuild: "resolve entrypoint after build",
  dependsOn: "Depends on",
  autoDescended: "Auto-resolved nested project root",
}

export function buildPageText(t: TFunction, key: string) {
  return t("builds") === "构建部署" ? zh[key] || key : en[key] || key
}
