import type { Locale } from "@/i18n"

export const FORM_COPY = {
  "zh-CN": {
    newConfig: "新增 MCP Config",
    editConfig: "编辑",
    formDesc: "表单支持受管 Stdio、外部 HTTP 和受管 HTTP；复杂字段仍可在 JSON 中保留。",
    parseErrorPrefix: "JSON / 预检查失败：",
    credentialErrorPrefix: "凭据列表加载失败：",
    localErrors: "保存前本地预检查错误",
    localWarnings: "本地配置提醒",
    sensitiveEnv: "已识别敏感环境变量",
    sensitiveEnvHint: "建议使用凭据引用，避免把明文密钥写入 Manifest。",
    serverId: "服务 ID",
    serverIdDesc: "MCP Server 的唯一标识，只能包含字母、数字、点、下划线和短横线。",
    name: "名称",
    nameDesc: "Console 中展示的服务名称，建议使用容易识别的业务名称。",
    runtimeMode: "运行方式",
    runtimeModeDesc: "选择 Lingshu Gate 如何获得服务，以及使用哪种 MCP 传输连接。",
    managedStdio: "受管 Stdio",
    managedStdioDesc: "由 Lingshu Gate 启动本地可执行进程，通过标准输入输出交互。",
    externalHttp: "外部 HTTP",
    externalHttpDesc: "服务独立运行在外部，Lingshu Gate 仅负责 streamable_http 连接。",
    managedHttp: "受管 HTTP",
    managedHttpDesc: "由 Lingshu Gate 启动后台服务，并等待其 HTTP 端口就绪建立连接。",
    advancedMode: "高级模式",
    advancedModeDesc: "保留当前 Manifest 的复杂运行与传输配置，仅在 JSON 中直接编辑。",
    advancedModeHint: "当前 Manifest 使用表单尚未覆盖的运行组合。应用表单时会原样保留 launch、transport、auto_start 与 restart_policy，避免静默改写。",
    endpoint: "MCP 地址",
    endpointDesc: "streamable_http 地址，例如 http://127.0.0.1:3120/mcp。",
    externalManagedHint: "该服务由外部进程管理，Lingshu Gate 只负责连接或断开，不负责启动、停止或自动重启。",
    command: "启动命令",
    commandDesc: "managed_process 要执行的已安装可执行文件或绝对路径。",
    cwd: "工作目录",
    cwdDesc: "可选。命令启动时的工作目录，例如 /workspace。",
    args: "启动参数",
    argsDesc: "一行一个参数，保存时会同步到 launch.args。",
    env: "环境变量",
    envDesc: "一行一个 KEY=VALUE，敏感值建议使用 ${credential:ID}。",
    insertCredential: "插入凭据引用",
    insertCredentialDesc: "点击凭据后会插入一行 KEY=${credential:ID} 到环境变量。",
    timeoutSeconds: "超时秒数",
    timeoutSecondsDesc: "MCP 初始化和请求等待的默认超时时间。",
    autoStart: "开机自启",
    autoStartDesc: "仅记录运行意图；保存与应用配置均不会直接启动服务。",
    restartPolicy: "崩溃重启策略",
    restartPolicyDesc: "进程退出、启动失败、健康检查失败后的自动恢复策略。",
    maxAttempts: "最大尝试次数",
    maxAttemptsDesc: "达到次数后停止自动重启，0 表示不重试。",
    delaySeconds: "初始延迟",
    delaySecondsDesc: "第一次自动重启前等待的秒数。",
    backoff: "退避倍数",
    backoffDesc: "每次失败后的延迟增长倍数。",
    maxDelay: "最大延迟",
    maxDelayDesc: "退避后允许等待的最大秒数。",
    resetAfterSeconds: "重置计数",
    resetAfterSecondsDesc: "服务稳定运行超过该秒数后，重置当前重启尝试次数。",
    restartOnExit: "进程退出后重启",
    restartOnExitDesc: "开启后，非策略排除的退出会触发自动重启。",
    exitAllowlist: "退出码允许列表",
    exitAllowlistDesc: "逗号分隔。填写后只有这些退出码会触发重启。",
    exitBlocklist: "退出码阻止列表",
    exitBlocklistDesc: "逗号分隔。命中后不会自动重启，常用 0 表示正常退出不重启。",
    healthCheck: "健康检查探活",
    healthCheckDesc: "当前通过 MCP tools/list 检查已连接服务是否健康。",
    intervalSeconds: "检查间隔",
    intervalSecondsDesc: "两次健康检查之间的等待时间。",
    healthTimeoutSeconds: "检查超时",
    healthTimeoutSecondsDesc: "单次健康检查最多等待的时间。",
    failureThreshold: "失败阈值",
    failureThresholdDesc: "连续失败达到该次数后触发恢复策略。",
    endpointRequired: "HTTP 运行方式需要填写 transport.endpoint",
    endpointInvalid: "MCP 地址必须是有效的 HTTP/HTTPS URL",
    applyForm: "应用表单到 JSON",
    formatJson: "格式化 JSON",
    backendPrecheck: "后端预检查",
    saveAndApply: "保存配置",
    rawJson: "Manifest JSON",
    rawJsonDesc: "复杂字段可以继续在 JSON 中编辑；应用表单时会保留未在表单中展示的字段。",
    precheckFailed: "预检查失败：",
    backendPrecheckFailed: "后端预检查失败：",
    backendCheck: "后端预检查",
    notRecommended: "不建议应用",
    saveWithWarning: "可以保存，但建议确认警告",
    saveOk: "可以保存",
    errors: "错误",
    warnings: "警告",
    info: "信息",
    ok: "正常",
    idRequired: "id 不能为空",
    idPattern: "id 只能包含字母、数字、下划线、点和短横线",
    launchRequired: "launch 配置不能为空",
    transportRequired: "transport 配置不能为空",
    launchTypeRequired: "launch.type 不能为空",
    commandRequired: "managed_process 需要填写 launch.command",
    containerImageDigestError: "managed_container 镜像必须固定到小写 SHA-256 Digest",
    containerVolumesUnsupported: "不支持旧的 launch.volumes；请使用结构化只读 launch.mounts",
    containerMountsError: "launch.mounts 必须包含绝对 Source、非根且非受保护的绝对 Target，并且不能关闭 read_only；后端还会校验 Allowed Root",
    containerEnvironmentProtected: "managed_container Environment 不能覆盖 LINGSHU_GATE_* 或 Docker 进程控制",
    launchTypeWarning: "当前表单主要覆盖 managed_process；其它 launch.type 请检查 Manifest JSON",
    argsWarning: "launch.args 建议全部使用字符串",
    transportTypeRequired: "transport.type 不能为空",
    stdioLaunchError: "transport.type=stdio 要求 launch.type 为 managed_process 或 managed_container",
    streamableEndpointError: "streamable_http 需要填写 transport.endpoint",
    timeoutWarning: "timeout_seconds 建议设置为大于 0 的数字",
  },
  "en-US": {
    newConfig: "New MCP Config",
    editConfig: "Edit",
    formDesc: "The form supports managed Stdio, external HTTP, and managed HTTP. Complex fields remain available in JSON.",
    parseErrorPrefix: "JSON / precheck failed: ",
    credentialErrorPrefix: "Failed to load credentials: ",
    localErrors: "Local precheck errors before saving",
    localWarnings: "Local config warnings",
    sensitiveEnv: "Sensitive env detected",
    sensitiveEnvHint: "Use credential references instead of storing plaintext secrets in the Manifest.",
    serverId: "Server ID",
    serverIdDesc: "Unique MCP Server identifier. Use letters, numbers, dots, underscores, and hyphens only.",
    name: "Name",
    nameDesc: "Display name in Console. Use a clear business name.",
    runtimeMode: "Runtime Mode",
    runtimeModeDesc: "Choose how Lingshu Gate obtains the service and connects to its MCP transport.",
    managedStdio: "Managed Stdio",
    managedStdioDesc: "Lingshu Gate starts the process and connects over standard input/output.",
    externalHttp: "External HTTP",
    externalHttpDesc: "The service runs independently. Lingshu Gate only connects or disconnects.",
    managedHttp: "Managed HTTP",
    managedHttpDesc: "Lingshu Gate starts the process and waits for the HTTP MCP endpoint.",
    advancedMode: "Advanced Mode",
    advancedModeDesc: "Preserve the current runtime and transport configuration; edit it in JSON.",
    advancedModeHint: "This Manifest uses a runtime combination not covered by the form. Applying the form preserves launch, transport, auto_start, and restart_policy without silently rewriting them.",
    endpoint: "MCP Endpoint",
    endpointDesc: "Streamable HTTP endpoint, for example http://127.0.0.1:3120/mcp.",
    externalManagedHint: "This service is externally managed. Lingshu Gate only connects or disconnects and does not start, stop, or restart the process.",
    command: "Command",
    commandDesc: "Installed executable or absolute path used by managed_process.",
    cwd: "Working Directory",
    cwdDesc: "Optional command working directory, for example /workspace.",
    args: "Arguments",
    argsDesc: "One argument per line. Saved into launch.args.",
    env: "Environment Variables",
    envDesc: "One KEY=VALUE per line. Use ${credential:ID} for sensitive values.",
    insertCredential: "Insert Credential Reference",
    insertCredentialDesc: "Click a credential to insert KEY=${credential:ID} into env.",
    timeoutSeconds: "Timeout Seconds",
    timeoutSecondsDesc: "Default timeout for MCP initialization and requests.",
    autoStart: "Auto Start",
    autoStartDesc: "Records runtime intent only; saving or applying does not directly start the server.",
    restartPolicy: "Restart Policy",
    restartPolicyDesc: "Auto recovery policy after process exit, startup failure, or health-check failure.",
    maxAttempts: "Max Attempts",
    maxAttemptsDesc: "Stop auto restart after this count. 0 means no retry.",
    delaySeconds: "Initial Delay",
    delaySecondsDesc: "Seconds to wait before the first auto restart.",
    backoff: "Backoff Multiplier",
    backoffDesc: "Delay growth multiplier after each failure.",
    maxDelay: "Max Delay",
    maxDelayDesc: "Maximum delay after backoff.",
    resetAfterSeconds: "Reset After",
    resetAfterSecondsDesc: "Reset restart attempts after the server stays stable for this duration.",
    restartOnExit: "Restart On Exit",
    restartOnExitDesc: "Restart automatically when the exit code is not excluded by policy.",
    exitAllowlist: "Exit Code Allowlist",
    exitAllowlistDesc: "Comma separated. When set, only these exit codes trigger restart.",
    exitBlocklist: "Exit Code Blocklist",
    exitBlocklistDesc: "Comma separated. Matching codes will not restart. 0 usually means normal exit.",
    healthCheck: "Health Check",
    healthCheckDesc: "Uses MCP tools/list to check whether the connected service is healthy.",
    intervalSeconds: "Interval",
    intervalSecondsDesc: "Delay between health checks.",
    healthTimeoutSeconds: "Timeout",
    healthTimeoutSecondsDesc: "Maximum wait time for one health check.",
    failureThreshold: "Failure Threshold",
    failureThresholdDesc: "Trigger recovery after this many consecutive failures.",
    endpointRequired: "HTTP runtime modes require transport.endpoint",
    endpointInvalid: "MCP endpoint must be a valid HTTP/HTTPS URL",
    applyForm: "Apply Form to JSON",
    formatJson: "Format JSON",
    backendPrecheck: "Backend Precheck",
    saveAndApply: "Save Config",
    rawJson: "Manifest JSON",
    rawJsonDesc: "Complex fields remain editable in JSON. Applying the form preserves fields not represented above.",
    precheckFailed: "Precheck failed: ",
    backendPrecheckFailed: "Backend precheck failed: ",
    backendCheck: "Backend Precheck",
    notRecommended: "Not recommended to apply",
    saveWithWarning: "Can save, but review warnings first",
    saveOk: "Can save",
    errors: "Errors",
    warnings: "Warnings",
    info: "Info",
    ok: "OK",
    idRequired: "id is required",
    idPattern: "id may only contain letters, numbers, underscores, dots, and hyphens",
    launchRequired: "launch config is required",
    transportRequired: "transport config is required",
    launchTypeRequired: "launch.type is required",
    commandRequired: "managed_process requires launch.command",
    containerImageDigestError: "managed_container images must be pinned by a lowercase SHA-256 digest",
    containerVolumesUnsupported: "launch.volumes is not supported; use structured read-only launch.mounts",
    containerMountsError: "launch.mounts requires absolute sources, non-root absolute targets outside protected paths, and read_only cannot be disabled; the backend also enforces the allowed root",
    containerEnvironmentProtected: "managed_container environment cannot override LINGSHU_GATE_* or Docker process controls",
    launchTypeWarning: "This form mainly covers managed_process. Check Manifest JSON for other launch.type values.",
    argsWarning: "launch.args should all be strings",
    transportTypeRequired: "transport.type is required",
    stdioLaunchError: "transport.type=stdio requires launch.type to be managed_process or managed_container",
    streamableEndpointError: "streamable_http requires transport.endpoint",
    timeoutWarning: "timeout_seconds should be greater than 0",
  },
} satisfies Record<Locale, Record<string, string>>

